### ISSUE TITLE
[Question] Testing 

### ISSUE THREAD

**Issue by Cacus3** [DragonX-cloud/dji_flutter_plugin#6]
Hi in description you say about a testing and it's required a drone and RC controller. Is there any option to test app with some simulation?

I borrow my drone but I want to give a try how this plugin work :) also when testing I don't want to go outside with drone with every change I made in code.

I really hope there is some app Simulator :)

**Comment by orenagiv** [comment]
Hey @Cacus3 

DJI simulator requires to have a real drone connected to the computer in order to work. 

So in order to really use the plugin, and run the example app - you need to do all the registration steps as required by DJI and specified in the Readme, and also connect a real drone - and then use the DJI simulator. 

However, if you don't have a drone at all, and just want to get all the configurations and your local development environment ready - you can get the example app running on a real device in Flutter debug mode, and test the "register" method (even without being connected to a drone at all). 
But that's the only method that will work without a drone :)

**Comment by orenagiv** [comment]
Hey @Cacus3 
I hope my reply above answered your question.

If not - please post another comment.
Meanwhile, I'm closing this issue.
